### ISSUE TITLE
Der theoretische Fall eines Ausfalls eines Vorstandmitglieds

### ISSUE THREAD

**Issue by Pellinger** [contao-association/association#18]
Tritt ein Mitglied des Vorstands zurück oder fällt, warum auch immer, aus, ist die Frage, wie der Vorstand aufgestellt ist, da nach §9 ein Vielfaches von 2 Beisitzern benötigt ist. Ähnliches gilt, wenn Präsident, Schatzmeister oder Sekretär ausfällt.

Unklar ist auch, welche Form ein Zurücktreten des Vorstands haben muss, z.B. Schriftform.

**Comment by may17** [comment]
Hier würde ich @‭‭‭‭cliffparnitzky fragen da er Jahrelange Erfahrung mit Vereinen hat. Hier steht leider auch nichts dazu http://www.vitaminb.ch/vereinswissen/vorstand

**Comment by aschempp** [comment]
Gemäss Vorstands-Call vom 12. Februar 2019 wird das Thema vorerst nicht weiter verfolgt.
